---
suites:
  - name: default
    run_list:
      - recipe[osl-docker::default]
  - name: powerci
    run_list:
      - recipe[osl-docker::powerci]
    excludes:
      - debian-8
  - name: workstation
    run_list:
      - recipe[osl-docker::workstation]
    excludes:
      - centos-7.4
